// ===================================================
// GSAP ANIMATIONS - HOMEPAGE ONLY
// ===================================================

gsap.registerPlugin(ScrollTrigger);

document.addEventListener('DOMContentLoaded', () => {
    
    // Add class to body so CSS knows GSAP is ready
    document.body.classList.add('gsap-loaded');

    // ===================================================
    // PAGE LOAD ANIMATIONS
    // ===================================================
    
    const loadTimeline = gsap.timeline({
        defaults: {
            ease: "power3.out",
            duration: 0.8
        }
    });

    // Hero Image - Fade in and scale up
    loadTimeline.fromTo(".hero-image-wrapper", 
        {
            opacity: 0,
            y: 60,
            scale: 0.95
        },
        {
            opacity: 1,
            y: 0,
            scale: 1,
            duration: 1
        }
    );

    // Title - Slide up
    loadTimeline.fromTo(".hero-title",
        {
            opacity: 0,
            y: 40
        },
        {
            opacity: 1,
            y: 0
        },
        "-=0.6" // Overlap with previous
    );

    // Description - Fade in
    loadTimeline.fromTo(".hero-container > p",
        {
            opacity: 0,
            y: 30
        },
        {
            opacity: 0.7, // Your original opacity
            y: 0
        },
        "-=0.5"
    );

    // Search bar - Slide up
    loadTimeline.fromTo(".search-wrapper",
        {
            opacity: 0,
            y: 30
        },
        {
            opacity: 1,
            y: 0
        },
        "-=0.4"
    );

    // Cast Section - Fade in with slight scale
    loadTimeline.fromTo(".cast-section",
        {
            opacity: 0,
            y: 40,
            scale: 0.98
        },
        {
            opacity: 1,
            y: 0,
            scale: 1,
            duration: 0.6
        },
        "-=0.3"
    );

    // Floating Dock - Pop up from bottom
    loadTimeline.fromTo(".floating-dock",
        {
            opacity: 0,
            y: 50
        },
        {
            opacity: 1,
            y: 0,
            ease: "back.out(1.5)",
            duration: 0.6
        },
        "-=0.3"
    );

    // ===================================================
    // SCROLL ANIMATIONS - Chapter Cards
    // ===================================================

    // Wait for cards to be generated by main.js
    setTimeout(() => {
        const cards = document.querySelectorAll('.chapter-card');
        
        if (cards.length > 0) {
            // Set initial state
            gsap.set(cards, {
                opacity: 0,
                y: 60
            });

            // Animate each card when it enters viewport
            cards.forEach((card, index) => {
                gsap.to(card, {
                    opacity: 1,
                    y: 0,
                    duration: 0.6,
                    ease: "power2.out",
                    scrollTrigger: {
                        trigger: card,
                        start: "top 85%", // When card top hits 85% of viewport
                        toggleActions: "play none none none"
                    },
                    delay: index * 0.1 // Stagger effect
                });
            });
        }
    }, 100); // Small delay to let main.js create cards

    // ===================================================
    // BONUS: Parallax on Hero Image (Subtle)
    // ===================================================

    gsap.to(".hero-image", {
        y: 50,
        ease: "none",
        scrollTrigger: {
            trigger: ".hero-container",
            start: "top top",
            end: "bottom top",
            scrub: 1 // Smooth parallax
        }
    });

    // ===================================================
    // BONUS: Cast Section Reveal on Scroll
    // ===================================================

    ScrollTrigger.create({
        trigger: ".cast-section",
        start: "top 80%",
        onEnter: () => {
            gsap.to(".cast-image", {
                scale: 1.05,
                duration: 0.8,
                ease: "power2.out"
            });
            gsap.to(".cast-info", {
                y: -5,
                duration: 0.6,
                ease: "power2.out"
            });
        },
        onLeaveBack: () => {
            gsap.to(".cast-image", {
                scale: 1,
                duration: 0.5
            });
            gsap.to(".cast-info", {
                y: 0,
                duration: 0.4
            });
        },
        // Glitchy entrance - perfect for "Gods Rank"
loaderTimeline.call(() => {
  musicModal.style.visibility = 'visible';
  
  const tl = gsap.timeline();
  
  // Background fade
  tl.to(musicModal, {
    duration: 0.3,
    opacity: 1,
    ease: "power2.out"
  })
  // Glitch effect on content
  .from(".music-modal-content", {
    duration: 0.1,
    x: -10,
    opacity: 0,
  })
  .to(".music-modal-content", {
    duration: 0.1,
    x: 10,
  })
  .to(".music-modal-content", {
    duration: 0.1,
    x: -5,
  })
  .to(".music-modal-content", {
    duration: 0.1,
    x: 0,
  })
  // Icon spins in
  .from(".music-icon", {
    duration: 0.6,
    scale: 0,
    rotation: 360,
    ease: "power4.out"
  }, "-=0.2")
  // Text glitches in
  .from(".music-title", {
    duration: 0.4,
    opacity: 0,
    skewX: 20,
    ease: "power4.out"
  })
  .from(".music-subtitle", {
    duration: 0.3,
    opacity: 0,
    ease: "power2.out"
  })
  // Buttons slide from sides
  .from(".music-yes", {
    duration: 0.5,
    x: -50,
    opacity: 0,
    ease: "power3.out"
  })
  .from(".music-no", {
    duration: 0.5,
    x: 50,
    opacity: 0,
    ease: "power3.out"
  }, "-=0.4")
  .from(".music-hint", {
    duration: 0.3,
    opacity: 0
  });

}, null, 7.2);
    });

});
